name: Windows_In_Browser

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable RDP
        run: |
          net user kamel123 MyStrong123 /add
          net localgroup administrators kamel123 /add
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0

      - name: Install Web-RDP
        run: |
          # تثبيت أداة تفتح الويندوز كصفحة ويب
          pip install webssh
          
      - name: Start Browser Access
        run: |
          # استخدام خدمة Pinggy لفتح رابط ويب مباشر للمتصفح
          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:3389 a.pinggy.io
