name: RDP_Pinggy_Final

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable RDP
        shell: pwsh
        run: |
          # 1. إنشاء المستخدم وتفعيل الـ RDP
          net user kamel123 MyStrong123 /add
          net localgroup administrators kamel123 /add
          
          # 2. إعدادات النظام لقبول الاتصال البعيد
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          
          # 3. تخطي المصادقة المعقدة لضمان عمل الاتصال عبر النفق
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name 'UserAuthentication' -Value 0

      - name: Start Pinggy Tunnel
        shell: pwsh
        run: |
          # إضافة خيار -T وخيار ServerAlive لضمان طباعة الرابط فوراً في السجلات
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -T -p 443 -R0:localhost:3389 a.pinggy.io
